<a href="https://colab.research.google.com/github/SUBHASH-KANDHWAY/MACHINE-LEARNING-PROJECTS/blob/master/pytorch_tutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import numpy as np
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [2]:
np.random.seed(42)

In [3]:
a=np.random.randn(3,3)

In [4]:
print(a)

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]


In [7]:
torch.manual_seed(40) 

In [8]:
a=torch.randn()

TypeError: ignored

In [9]:
a=np.random.randn(3,3)
b=np.random.randn(3,3)
print(np.dot(a,b))
print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))

[[-0.13449362 -0.84921327  1.99150793]
 [ 1.15128124 -0.66225694  5.06594361]
 [ 0.56817306  0.76058322  0.25721662]]
[[-0.36546403 -1.87572139  0.99991902]
 [ 0.01618597 -1.84575204 -3.14966602]
 [-1.10667025 -0.90190853 -0.83674624]]
[[ 1.45058412  0.94888601 -1.93137852]
 [ 0.46773857 -1.98080845 -0.30016965]
 [-0.0179048  -1.12375371  1.46524091]]
[[ -0.59751724   0.32812892  -0.31776355]
 [ -1.0716903  -28.33305363   1.2106826 ]
 [  1.0328901   -9.13097254  -0.27302266]]


In [ ]:
print(np.transpose(np.divide(a,b)))

[[  0.78242563   1.4680216    2.07097081]
 [  0.74667582  -4.3708542  -12.4683882 ]
 [  0.26704742   0.37131242   0.83045489]]


In [ ]:
import torch
a=torch.randn(3,3)
torch.t(a)
print(type(a))

<class 'torch.Tensor'>


In [ ]:
b=torch.tensor(1)
print(b)

tensor(1)


In [ ]:
c=torch.tensor(5)
print(b)

tensor(1)


In [ ]:
import torch
torch.cat((c,b),dim=1)

RuntimeError: ignored

In [10]:
x=np.array([[1,3,4],[9,9,8]])

In [11]:
tensor=torch.from_numpy(x)
print(x)

[[1 3 4]
 [9 9 8]]


In [12]:
n =torch.randn(2,4)
print(n)

tensor([[ 0.9307, -0.3482,  0.8855, -0.4909],
        [-0.4273,  0.9385,  1.1841,  0.5234]])


In [13]:
m=torch.ones((2,2),requires_grad=True)
print(m)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [14]:
b=m+5
c=b.mean()
print(b,m)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>) tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [15]:
c.backward()

In [16]:
print(m.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [17]:
##from torch import optim
##adam=optim.Adam(model.parameters(),lr=)

In [42]:
x=torch.Tensor([[1,0,1,1],[1,0,1,0],[0,1,0,1]])
y=torch.Tensor([[1,1,0,1]])
print(x,'\n')
print(y)
print(x.shape)
print(y.shape)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 0.],
        [0., 1., 0., 1.]]) 

tensor([[1., 1., 0., 1.]])
torch.Size([3, 4])
torch.Size([1, 4])


In [31]:
def sigmoid(x):
  return 1/(1+torch.exp(-x))

def derivative_sig(x):
  return sigmoid(x)*(1-sigmoid(x))

In [27]:
epoch=7000
lr=.1
inputlayer_neurons=x.shape[1]
hidden_layer=3
outlayer_neurons=1


In [28]:
##weight and bias initialisation initialisation
weight=torch.randn(inputlayer_neurons,hidden_layer).type(torch.FloatTensor)
bias=torch.randn(1,hidden_layer).type(torch.FloatTensor)
output_weight=torch.randn(hidden_layer,outlayer_neurons)
output_bias=torch.randn(1,outlayer_neurons)

In [43]:
for i in range(epoch):
  #forwordpropagation
  hiddenlayer__input1=torch.mm(x,weight)
  hiddenlayer__input=hiddenlayer__input1+bias
  hiddenlayer__input_activation=sigmoid(hiddenlayer__input)

  outputlayer_input1=torch.mm(hiddenlayer__input_activation,output_weight)
  outputlayer_input=outputlayer_input1+output_bias
  output=sigmoid(outputlayer_input)


  #backpropagation
  E=y-output
  slope_output_layer=derivative_sig(output)
  slope_hidden_layer=derivative_sig(hiddenlayer__input_activation)
  d_output=E*slope_output_layer
  error_at_hidden_layer=torch.mm(d_output,output_weight.t())
  d_hiddenlayer=error_at_hidden_layer*slope_hidden_layer
  
  output_weight+=torch.mm(hiddenlayer__input_activation)
  output_bias+=d_output.sum()*lr
  weight+=torch.mm(x.t(),d_hiddenlayer)*lr
  bias+=d_output.sum()*lr

RuntimeError: ignored

In [ ]:
print('ACTUAL:\n',y)
print('PRIDICTED:\n',output)